#ifndef DEVELCONTROL_GLOBAL_H
#define DEVELCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STABLEPROPERTIESWINDOW_LIBRARY)
#  define STABLEPROPERTIESWINDOW_EXPORT Q_DECL_EXPORT
#else
#  define STABLEPROPERTIESWINDOW_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVELCONTROL_GLOBAL_H
