.\" Man Page for meta-set
.TH "meta-set" "1"
.SH "NAME"
meta-set \- utils for get file meta info.
.SH "SYNOPSIS"
.B meta-set [OPTION] <path> [keys..]
.SH "DESCRIPTION"
meta-set
This program provides several commands for set file meta info.
.TP
\fB -t, --tree\fR
Tree
.TP
\fB -u, --unset\fR
Unset
.TP
\fB -l, --list\fR
Set as list
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://gitee.com/openkylin/peony/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
Yue Lan <lanyue@kylinos.cn> (2024)
