.\" Man Page for update-desktop-grid.sh
.TH "update-desktop-grid" "1"
.SH "NAME"
update-desktop-grid.sh \- utils for get file meta info.
.SH "SYNOPSIS"
.B update-desktop-grid.sh
.SH "DESCRIPTION"
This program will caculate all usres desktop item position info and convert them to grid position.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
https://gitee.com/openkylin/peony/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
Yue Lan <lanyue@kylinos.cn> (2024)
